<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class ProductsSeeder extends AbstractSeed
{
    public function run(): void
    {
        $this->execute('TRUNCATE TABLE products RESTART IDENTITY CASCADE');
        
        $data = [
            // 10 видов кофе (category_id = 1)
            ['id' => 1, 'name' => 'Кофе Эфиопия Yirgacheffe', 'slug' => 'coffee-ethiopia-yirgacheffe', 'description' => 'Ароматный свежеобжаренный кофе из Эфиопии', 'price' => 1200.00, 'old_price' => null, 'stock' => 10, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Эфиопия Yirgacheffe', 'meta_description' => 'Свежеобжаренный кофе из Эфиопии', 'rating' => 4.8, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 2, 'name' => 'Кофе Бразилия Santos', 'slug' => 'coffee-brazil-santos', 'description' => 'Классический кофе из Бразилии', 'price' => 1100.00, 'old_price' => 1150.00, 'stock' => 12, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Бразилия Santos', 'meta_description' => 'Классика из Бразилии', 'rating' => 4.6, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 3, 'name' => 'Кофе Колумбия Supremo', 'slug' => 'coffee-colombia-supremo', 'description' => 'Яркий кофе из Колумбии', 'price' => 1300.00, 'old_price' => null, 'stock' => 8, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Колумбия Supremo', 'meta_description' => 'Колумбийский кофе', 'rating' => 4.7, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 4, 'name' => 'Кофе Кения AA', 'slug' => 'coffee-kenya-aa', 'description' => 'Кислинка и фруктовый вкус', 'price' => 1350.00, 'old_price' => 1400.00, 'stock' => 6, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Кения AA', 'meta_description' => 'Кенийский кофе', 'rating' => 4.5, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 5, 'name' => 'Кофе Гватемала Antigua', 'slug' => 'coffee-guatemala-antigua', 'description' => 'Шоколадный оттенок, средней обжарки', 'price' => 1250.00, 'old_price' => null, 'stock' => 9, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Гватемала Antigua', 'meta_description' => 'Гватемальский кофе', 'rating' => 4.4, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 6, 'name' => 'Кофе Йемен Mocha', 'slug' => 'coffee-yemen-mocha', 'description' => 'Редкий сорт с винными нотами', 'price' => 1400.00, 'old_price' => null, 'stock' => 5, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Йемен Mocha', 'meta_description' => 'Йеменский кофе', 'rating' => 4.9, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 7, 'name' => 'Кофе Уганда Bugisu', 'slug' => 'coffee-uganda-bugisu', 'description' => 'Плотный вкус, африканский кофе', 'price' => 1150.00, 'old_price' => 1200.00, 'stock' => 7, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Уганда Bugisu', 'meta_description' => 'Африканский кофе', 'rating' => 4.3, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 8, 'name' => 'Кофе Азия Sumatra', 'slug' => 'coffee-asia-sumatra', 'description' => 'Насыщенный индонезийский кофе', 'price' => 1200.00, 'old_price' => null, 'stock' => 10, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Азия Sumatra', 'meta_description' => 'Индонезийский кофе', 'rating' => 4.2, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 9, 'name' => 'Кофе Латинская Америка Blend', 'slug' => 'coffee-latin-america-blend', 'description' => 'Смесь лучших сортов Латинской Америки', 'price' => 1100.00, 'old_price' => null, 'stock' => 15, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Латинская Америка Blend', 'meta_description' => 'Латиноамериканский кофе', 'rating' => 4.1, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 10, 'name' => 'Кофе Микролот Panama', 'slug' => 'coffee-microlot-panama', 'description' => 'Эксклюзивный микролот Панамы', 'price' => 2000.00, 'old_price' => 2200.00, 'stock' => 3, 'weight' => 250, 'category_id' => 1, 'meta_title' => 'Кофе Микролот Panama', 'meta_description' => 'Панамский микролот', 'rating' => 5.0, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            // 10 видов чая и кофейных напитков (category_id = 2)
            ['id' => 11, 'name' => 'Чай Сенча', 'slug' => 'tea-sencha', 'description' => 'Зеленый чай японского типа', 'price' => 600.00, 'old_price' => null, 'stock' => 20, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Сенча', 'meta_description' => 'Японский зеленый чай', 'rating' => 4.7, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 12, 'name' => 'Чай Ассам', 'slug' => 'tea-assam', 'description' => 'Крепкий индийский чай', 'price' => 550.00, 'old_price' => null, 'stock' => 18, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Ассам', 'meta_description' => 'Индийский черный чай', 'rating' => 4.5, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 13, 'name' => 'Чай Эрл Грей', 'slug' => 'tea-earl-grey', 'description' => 'Черный чай с бергамотом', 'price' => 650.00, 'old_price' => 700.00, 'stock' => 16, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Эрл Грей', 'meta_description' => 'Чай с бергамотом', 'rating' => 4.8, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 14, 'name' => 'Чай Пуэр', 'slug' => 'tea-puer', 'description' => 'Китайский выдержанный чай', 'price' => 700.00, 'old_price' => 750.00, 'stock' => 10, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Пуэр', 'meta_description' => 'Китайский чай Пуэр', 'rating' => 4.4, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 15, 'name' => 'Чай Матча', 'slug' => 'tea-matca', 'description' => 'Японский порошковый зеленый чай', 'price' => 950.00, 'old_price' => 1000.00, 'stock' => 9, 'weight' => 50, 'category_id' => 2, 'meta_title' => 'Чай Матча', 'meta_description' => 'Матча зеленый чай', 'rating' => 4.9, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 16, 'name' => 'Чай Молочный улун', 'slug' => 'tea-milk-yun', 'description' => 'Нежный улун с молочным вкусом', 'price' => 800.00, 'old_price' => null, 'stock' => 8, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Молочный улун', 'meta_description' => 'Молочный улун', 'rating' => 4.6, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 17, 'name' => 'Чай Травяной', 'slug' => 'tea-tea', 'description' => 'Смесь трав для заваривания', 'price' => 500.00, 'old_price' => null, 'stock' => 14, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай Травяной', 'meta_description' => 'Травяной чай', 'rating' => 4.2, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 18, 'name' => 'Кофейный напиток Капучино', 'slug' => 'coffee-cappuccino', 'description' => 'Растворимый напиток с молоком', 'price' => 750.00, 'old_price' => null, 'stock' => 11, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Капучино', 'meta_description' => 'Кофейный напиток', 'rating' => 4.3, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 19, 'name' => 'Кофейный напиток Латте', 'slug' => 'coffee-latte', 'description' => 'Нежный кофейный напиток', 'price' => 750.00, 'old_price' => 800.00, 'stock' => 10, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Латте', 'meta_description' => 'Кофейный напиток Латте', 'rating' => 4.0, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 20, 'name' => 'Чай Зеленый с жасмином', 'slug' => 'tea-green-with-jasmine', 'description' => 'Зеленый чай с цветами жасмина', 'price' => 650.00, 'old_price' => null, 'stock' => 13, 'weight' => 100, 'category_id' => 2, 'meta_title' => 'Чай с жасмином', 'meta_description' => 'Зеленый чай с жасмином', 'rating' => 4.8, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            // 10 товаров для вендинга (category_id = 3)
            ['id' => 21, 'name' => 'Гранулированный кофе', 'slug' => 'coffee-ground', 'description' => 'Растворимый гранулированный кофе', 'price' => 800.00, 'old_price' => null, 'stock' => 30, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Гранулированный кофе', 'meta_description' => 'Кофе для вендинга', 'rating' => 4.5, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 22, 'name' => 'Гранулированный цикорий', 'slug' => 'coffee-cicory-ground', 'description' => 'Цикорий для вендинга', 'price' => 650.00, 'old_price' => null, 'stock' => 25, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Гранулированный цикорий', 'meta_description' => 'Цикорий для вендинга', 'rating' => 4.3, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 23, 'name' => 'Зерновой кофе', 'slug' => 'coffee-bean', 'description' => 'Кофе в зернах для автоматов', 'price' => 1200.00, 'old_price' => 1300.00, 'stock' => 22, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Зерновой кофе', 'meta_description' => 'Кофе для вендинга', 'rating' => 4.6, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 24, 'name' => 'Гранулированный какао', 'slug' => 'coffee-cacao-ground', 'description' => 'Какао для вендинга', 'price' => 700.00, 'old_price' => null, 'stock' => 18, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Гранулированный какао', 'meta_description' => 'Какао для вендинга', 'rating' => 4.4, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 25, 'name' => 'Гранулированные кофейные напитки', 'slug' => 'coffee-coffee-drink-ground', 'description' => 'Смесь кофе и молока', 'price' => 850.00, 'old_price' => 900.00, 'stock' => 15, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Гранулированные кофейные напитки', 'meta_description' => 'Кофейные напитки для вендинга', 'rating' => 4.1, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 26, 'name' => 'Кофе порошкообразный', 'slug' => 'coffee-ground-powder', 'description' => 'Порошковый кофе для автоматов', 'price' => 900.00, 'old_price' => null, 'stock' => 12, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Кофе порошкообразный', 'meta_description' => 'Порошковый кофе', 'rating' => 4.0, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 27, 'name' => 'Сухое молоко гранулированное', 'slug' => 'dried-milk-ground', 'description' => 'Молоко для вендинговых автоматов', 'price' => 600.00, 'old_price' => null, 'stock' => 17, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Сухое молоко гранулированное', 'meta_description' => 'Сухое молоко для вендинга', 'rating' => 4.2, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 28, 'name' => 'Гранулированный чай', 'slug' => 'tea-ground', 'description' => 'Чай для вендинга', 'price' => 550.00, 'old_price' => null, 'stock' => 20, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Гранулированный чай', 'meta_description' => 'Чай для вендинга', 'rating' => 4.3, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 29, 'name' => 'Горячий шоколад', 'slug' => 'hot-chocolate', 'description' => 'Напиток для вендинговых автоматов', 'price' => 950.00, 'old_price' => 1000.00, 'stock' => 13, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Горячий шоколад', 'meta_description' => 'Шоколад для вендинга', 'rating' => 4.7, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 30, 'name' => 'Растворимый кофе вендинг', 'slug' => 'dissolvable-coffee', 'description' => 'Растворимый кофе для автоматов', 'price' => 850.00, 'old_price' => null, 'stock' => 11, 'weight' => 500, 'category_id' => 3, 'meta_title' => 'Растворимый кофе вендинг', 'meta_description' => 'Кофе для вендинга', 'rating' => 4.1, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            // 10 товаров для здорового питания (category_id = 4)
            ['id' => 31, 'name' => 'Цикорий и корень цикория', 'slug' => 'cicory-root', 'description' => 'Здоровый заменитель кофе из цикория', 'price' => 550.00, 'old_price' => null, 'stock' => 9, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Цикорий и корень цикория', 'meta_description' => 'Цикорий для здоровья', 'rating' => 4.9, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 32, 'name' => 'Ячменные напитки', 'slug' => 'oatmeal-drink', 'description' => 'Напиток из ячменя', 'price' => 500.00, 'old_price' => null, 'stock' => 7, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Ячменные напитки', 'meta_description' => 'Ячменный напиток', 'rating' => 4.6, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 33, 'name' => 'Напитки для здоровья', 'slug' => 'health-drink', 'description' => 'Функциональные напитки для здоровья', 'price' => 700.00, 'old_price' => 750.00, 'stock' => 6, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Напитки для здоровья', 'meta_description' => 'Здоровое питание', 'rating' => 4.8, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 34, 'name' => 'Протеиновые смеси', 'slug' => 'protein-blend', 'description' => 'Смеси для спортивного питания', 'price' => 1500.00, 'old_price' => 1600.00, 'stock' => 5, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Протеиновые смеси', 'meta_description' => 'Протеин для здоровья', 'rating' => 4.5, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 35, 'name' => 'Толокняные каши', 'slug' => 'porridge', 'description' => 'Здоровая каша из толокна', 'price' => 400.00, 'old_price' => null, 'stock' => 11, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Толокняные каши', 'meta_description' => 'Каша для здоровья', 'rating' => 4.2, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 36, 'name' => 'Злаковые батончики', 'slug' => 'cereal-biscuit', 'description' => 'Полезные батончики для перекуса', 'price' => 350.00, 'old_price' => null, 'stock' => 10, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Злаковые батончики', 'meta_description' => 'Батончики для здоровья', 'rating' => 4.3, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 37, 'name' => 'Суперфуды', 'slug' => 'superfood', 'description' => 'Питательные суперфуды', 'price' => 2000.00, 'old_price' => 2100.00, 'stock' => 4, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Суперфуды', 'meta_description' => 'Суперфуды для здоровья', 'rating' => 4.9, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 38, 'name' => 'Органические смеси', 'slug' => 'organic-blend', 'description' => 'Органические продукты для здоровья', 'price' => 1700.00, 'old_price' => null, 'stock' => 8, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Органические смеси', 'meta_description' => 'Органика для здоровья', 'rating' => 4.7, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 39, 'name' => 'Безглютеновые продукты', 'slug' => 'gluten-free', 'description' => 'Продукты без глютена', 'price' => 900.00, 'old_price' => 950.00, 'stock' => 7, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Безглютеновые продукты', 'meta_description' => 'Безглютеновое питание', 'rating' => 4.6, 'is_active' => true, 'is_featured' => false, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => 40, 'name' => 'Веганские продукты', 'slug' => 'vegan', 'description' => 'Питание для веганов', 'price' => 1200.00, 'old_price' => null, 'stock' => 6, 'weight' => 200, 'category_id' => 4, 'meta_title' => 'Веганские продукты', 'meta_description' => 'Веганское питание', 'rating' => 4.8, 'is_active' => true, 'is_featured' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ];
        $this->table('products')->insert($data)->save();
    }
}
